# Form implementation generated from reading ui file 'adminwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=AdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 771, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setGeometry(QtCore.QRect(290, 0, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.tab)
        self.label_4.setGeometry(QtCore.QRect(60, 60, 71, 16))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.tab)
        self.label_5.setGeometry(QtCore.QRect(60, 100, 71, 16))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.tab)
        self.label_6.setGeometry(QtCore.QRect(60, 140, 71, 16))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.tab)
        self.label_7.setGeometry(QtCore.QRect(60, 180, 71, 16))
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.tab)
        self.label_8.setGeometry(QtCore.QRect(60, 220, 71, 16))
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.emp_nama = QtWidgets.QLineEdit(parent=self.tab)
        self.emp_nama.setGeometry(QtCore.QRect(160, 50, 241, 31))
        self.emp_nama.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.emp_nama.setObjectName("emp_nama")
        self.emp_username = QtWidgets.QLineEdit(parent=self.tab)
        self.emp_username.setGeometry(QtCore.QRect(160, 90, 241, 31))
        self.emp_username.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.emp_username.setObjectName("emp_username")
        self.emp_password = QtWidgets.QLineEdit(parent=self.tab)
        self.emp_password.setGeometry(QtCore.QRect(160, 130, 241, 31))
        self.emp_password.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.emp_password.setObjectName("emp_password")
        self.emp_salary = QtWidgets.QLineEdit(parent=self.tab)
        self.emp_salary.setGeometry(QtCore.QRect(160, 170, 241, 31))
        self.emp_salary.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.emp_salary.setObjectName("emp_salary")
        self.role = QtWidgets.QComboBox(parent=self.tab)
        self.role.setGeometry(QtCore.QRect(160, 210, 241, 31))
        self.role.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.role.setObjectName("role")
        self.emp_tambah = QtWidgets.QPushButton(parent=self.tab)
        self.emp_tambah.setGeometry(QtCore.QRect(240, 260, 161, 41))
        self.emp_tambah.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background: rgb(13, 110, 253)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(13, 110, 253, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(13, 110, 253, 200);\n"
"}\n"
"\n"
"")
        self.emp_tambah.setObjectName("emp_tambah")
        self.label_9 = QtWidgets.QLabel(parent=self.tab)
        self.label_9.setGeometry(QtCore.QRect(430, 50, 91, 16))
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.emp_refresh = QtWidgets.QPushButton(parent=self.tab)
        self.emp_refresh.setGeometry(QtCore.QRect(430, 380, 81, 31))
        self.emp_refresh.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(108, 117, 125);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(108, 117, 125, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(108, 117, 125, 200);\n"
"}")
        self.emp_refresh.setObjectName("emp_refresh")
        self.emp_hapus = QtWidgets.QPushButton(parent=self.tab)
        self.emp_hapus.setGeometry(QtCore.QRect(530, 380, 81, 31))
        self.emp_hapus.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(220, 53, 69);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(220, 53, 69, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(220, 53, 69, 200);\n"
"}")
        self.emp_hapus.setObjectName("emp_hapus")
        self.emp_edit = QtWidgets.QPushButton(parent=self.tab)
        self.emp_edit.setGeometry(QtCore.QRect(630, 380, 81, 31))
        self.emp_edit.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(25, 135, 84);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(25, 135, 84, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(25, 135, 84, 200);\n"
"}")
        self.emp_edit.setObjectName("emp_edit")
        self.label_10 = QtWidgets.QLabel(parent=self.tab)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 811, 601))
        self.label_10.setStyleSheet("border-image: url(Green and Orange Modern Grocery Store Banner Landscape (1).png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.table_emp = QtWidgets.QTableWidget(parent=self.tab)
        self.table_emp.setGeometry(QtCore.QRect(430, 70, 281, 301))
        self.table_emp.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.table_emp.setObjectName("table_emp")
        self.table_emp.setColumnCount(0)
        self.table_emp.setRowCount(0)
        self.label_10.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.emp_nama.raise_()
        self.emp_username.raise_()
        self.emp_password.raise_()
        self.emp_salary.raise_()
        self.role.raise_()
        self.emp_tambah.raise_()
        self.label_9.raise_()
        self.emp_refresh.raise_()
        self.emp_hapus.raise_()
        self.emp_edit.raise_()
        self.table_emp.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.barang_sellprice = QtWidgets.QLineEdit(parent=self.tab_2)
        self.barang_sellprice.setGeometry(QtCore.QRect(160, 130, 241, 31))
        self.barang_sellprice.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_sellprice.setObjectName("barang_sellprice")
        self.label_22 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(430, 50, 91, 16))
        self.label_22.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_22.setObjectName("label_22")
        self.barang_hapus = QtWidgets.QPushButton(parent=self.tab_2)
        self.barang_hapus.setGeometry(QtCore.QRect(530, 380, 81, 31))
        self.barang_hapus.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(220, 53, 69);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(220, 53, 69, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(220, 53, 69, 200);\n"
"}")
        self.barang_hapus.setObjectName("barang_hapus")
        self.barang_buyprice = QtWidgets.QLineEdit(parent=self.tab_2)
        self.barang_buyprice.setGeometry(QtCore.QRect(160, 90, 241, 31))
        self.barang_buyprice.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_buyprice.setObjectName("barang_buyprice")
        self.label_23 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(60, 60, 71, 16))
        self.label_23.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_23.setObjectName("label_23")
        self.barang_nama = QtWidgets.QLineEdit(parent=self.tab_2)
        self.barang_nama.setGeometry(QtCore.QRect(160, 50, 241, 31))
        self.barang_nama.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_nama.setObjectName("barang_nama")
        self.label_24 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(60, 100, 71, 16))
        self.label_24.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(300, 0, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_25.setObjectName("label_25")
        self.barang_edit = QtWidgets.QPushButton(parent=self.tab_2)
        self.barang_edit.setGeometry(QtCore.QRect(630, 380, 81, 31))
        self.barang_edit.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(25, 135, 84);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(25, 135, 84, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(25, 135, 84, 200);\n"
"}")
        self.barang_edit.setObjectName("barang_edit")
        self.barang_tambah = QtWidgets.QPushButton(parent=self.tab_2)
        self.barang_tambah.setGeometry(QtCore.QRect(240, 300, 161, 41))
        self.barang_tambah.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background: rgb(13, 110, 253)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(13, 110, 253, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(13, 110, 253, 200);\n"
"}\n"
"\n"
"")
        self.barang_tambah.setObjectName("barang_tambah")
        self.label_26 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(60, 140, 71, 16))
        self.label_26.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_26.setObjectName("label_26")
        self.barang_refresh = QtWidgets.QPushButton(parent=self.tab_2)
        self.barang_refresh.setGeometry(QtCore.QRect(430, 380, 81, 31))
        self.barang_refresh.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(108, 117, 125);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(108, 117, 125, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(108, 117, 125, 200);\n"
"}")
        self.barang_refresh.setObjectName("barang_refresh")
        self.label_27 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(60, 180, 71, 16))
        self.label_27.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(60, 220, 71, 16))
        self.label_28.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(60, 260, 71, 16))
        self.label_29.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_29.setObjectName("label_29")
        self.barang_quantity = QtWidgets.QLineEdit(parent=self.tab_2)
        self.barang_quantity.setGeometry(QtCore.QRect(160, 170, 241, 31))
        self.barang_quantity.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_quantity.setObjectName("barang_quantity")
        self.barang_supplier = QtWidgets.QComboBox(parent=self.tab_2)
        self.barang_supplier.setGeometry(QtCore.QRect(160, 210, 241, 31))
        self.barang_supplier.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_supplier.setObjectName("barang_supplier")
        self.barang_expired = QtWidgets.QDateEdit(parent=self.tab_2)
        self.barang_expired.setGeometry(QtCore.QRect(160, 250, 241, 31))
        self.barang_expired.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_expired.setObjectName("barang_expired")
        self.label_30 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(60, 340, 101, 16))
        self.label_30.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_30.setObjectName("label_30")
        self.barang_inputcheck = QtWidgets.QLineEdit(parent=self.tab_2)
        self.barang_inputcheck.setGeometry(QtCore.QRect(60, 370, 241, 41))
        self.barang_inputcheck.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_inputcheck.setObjectName("barang_inputcheck")
        self.barang_check = QtWidgets.QPushButton(parent=self.tab_2)
        self.barang_check.setGeometry(QtCore.QRect(320, 370, 81, 41))
        self.barang_check.setStyleSheet("color: rgb(0, 0, 0);")
        self.barang_check.setObjectName("barang_check")
        self.label_11 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(-10, 0, 811, 601))
        self.label_11.setStyleSheet("border-image: url(Green and Orange Modern Grocery Store Banner Landscape (1).png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.table_barang = QtWidgets.QTableWidget(parent=self.tab_2)
        self.table_barang.setGeometry(QtCore.QRect(430, 70, 281, 301))
        self.table_barang.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.table_barang.setObjectName("table_barang")
        self.table_barang.setColumnCount(0)
        self.table_barang.setRowCount(0)
        self.label_11.raise_()
        self.barang_sellprice.raise_()
        self.label_22.raise_()
        self.barang_hapus.raise_()
        self.barang_buyprice.raise_()
        self.label_23.raise_()
        self.barang_nama.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.barang_edit.raise_()
        self.barang_tambah.raise_()
        self.label_26.raise_()
        self.barang_refresh.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.barang_quantity.raise_()
        self.barang_supplier.raise_()
        self.barang_expired.raise_()
        self.label_30.raise_()
        self.barang_inputcheck.raise_()
        self.barang_check.raise_()
        self.table_barang.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.supp_nama = QtWidgets.QLineEdit(parent=self.tab_3)
        self.supp_nama.setGeometry(QtCore.QRect(160, 50, 241, 31))
        self.supp_nama.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.supp_nama.setObjectName("supp_nama")
        self.supp_edit = QtWidgets.QPushButton(parent=self.tab_3)
        self.supp_edit.setGeometry(QtCore.QRect(630, 380, 81, 31))
        self.supp_edit.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(25, 135, 84);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(25, 135, 84, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(25, 135, 84, 200);\n"
"}")
        self.supp_edit.setObjectName("supp_edit")
        self.supp_refresh = QtWidgets.QPushButton(parent=self.tab_3)
        self.supp_refresh.setGeometry(QtCore.QRect(430, 380, 81, 31))
        self.supp_refresh.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(108, 117, 125);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(108, 117, 125, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(108, 117, 125, 200);\n"
"}")
        self.supp_refresh.setObjectName("supp_refresh")
        self.supp_tambah = QtWidgets.QPushButton(parent=self.tab_3)
        self.supp_tambah.setGeometry(QtCore.QRect(240, 180, 161, 41))
        self.supp_tambah.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background: rgb(13, 110, 253)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(13, 110, 253, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(13, 110, 253, 200);\n"
"}\n"
"\n"
"")
        self.supp_tambah.setObjectName("supp_tambah")
        self.label_12 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(60, 100, 71, 16))
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(60, 140, 71, 16))
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(300, 0, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(60, 60, 71, 16))
        self.label_15.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(430, 50, 91, 16))
        self.label_16.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_16.setObjectName("label_16")
        self.supp_contact = QtWidgets.QLineEdit(parent=self.tab_3)
        self.supp_contact.setGeometry(QtCore.QRect(160, 90, 241, 31))
        self.supp_contact.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.supp_contact.setObjectName("supp_contact")
        self.supp_alamat = QtWidgets.QLineEdit(parent=self.tab_3)
        self.supp_alamat.setGeometry(QtCore.QRect(160, 130, 241, 31))
        self.supp_alamat.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.supp_alamat.setObjectName("supp_alamat")
        self.supp_hapus = QtWidgets.QPushButton(parent=self.tab_3)
        self.supp_hapus.setGeometry(QtCore.QRect(530, 380, 81, 31))
        self.supp_hapus.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(220, 53, 69);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(220, 53, 69, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(220, 53, 69, 200);\n"
"}")
        self.supp_hapus.setObjectName("supp_hapus")
        self.label_31 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(-10, 0, 811, 601))
        self.label_31.setStyleSheet("border-image: url(Green and Orange Modern Grocery Store Banner Landscape (1).png);")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.table_supp = QtWidgets.QTableWidget(parent=self.tab_3)
        self.table_supp.setGeometry(QtCore.QRect(430, 70, 281, 301))
        self.table_supp.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.table_supp.setObjectName("table_supp")
        self.table_supp.setColumnCount(0)
        self.table_supp.setRowCount(0)
        self.label_31.raise_()
        self.supp_nama.raise_()
        self.supp_edit.raise_()
        self.supp_refresh.raise_()
        self.supp_tambah.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.supp_contact.raise_()
        self.supp_alamat.raise_()
        self.supp_hapus.raise_()
        self.table_supp.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.cust_tambah = QtWidgets.QPushButton(parent=self.tab_4)
        self.cust_tambah.setGeometry(QtCore.QRect(240, 180, 161, 41))
        self.cust_tambah.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background: rgb(13, 110, 253)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(13, 110, 253, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(13, 110, 253, 200);\n"
"}\n"
"\n"
"")
        self.cust_tambah.setObjectName("cust_tambah")
        self.cust_edit = QtWidgets.QPushButton(parent=self.tab_4)
        self.cust_edit.setGeometry(QtCore.QRect(630, 380, 81, 31))
        self.cust_edit.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(25, 135, 84);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(25, 135, 84, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(25, 135, 84, 200);\n"
"}")
        self.cust_edit.setObjectName("cust_edit")
        self.label_17 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(60, 100, 71, 16))
        self.label_17.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.cust_nama = QtWidgets.QLineEdit(parent=self.tab_4)
        self.cust_nama.setGeometry(QtCore.QRect(160, 50, 241, 31))
        self.cust_nama.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cust_nama.setObjectName("cust_nama")
        self.cust_alamat = QtWidgets.QLineEdit(parent=self.tab_4)
        self.cust_alamat.setGeometry(QtCore.QRect(160, 130, 241, 31))
        self.cust_alamat.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cust_alamat.setObjectName("cust_alamat")
        self.cust_hapus = QtWidgets.QPushButton(parent=self.tab_4)
        self.cust_hapus.setGeometry(QtCore.QRect(530, 380, 81, 31))
        self.cust_hapus.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(220, 53, 69);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(220, 53, 69, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(220, 53, 69, 200);\n"
"}")
        self.cust_hapus.setObjectName("cust_hapus")
        self.cust_contact = QtWidgets.QLineEdit(parent=self.tab_4)
        self.cust_contact.setGeometry(QtCore.QRect(160, 90, 241, 31))
        self.cust_contact.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cust_contact.setObjectName("cust_contact")
        self.cust_refresh = QtWidgets.QPushButton(parent=self.tab_4)
        self.cust_refresh.setGeometry(QtCore.QRect(430, 380, 81, 31))
        self.cust_refresh.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(108, 117, 125);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(108, 117, 125, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(108, 117, 125, 200);\n"
"}")
        self.cust_refresh.setObjectName("cust_refresh")
        self.label_18 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(60, 140, 71, 16))
        self.label_18.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(430, 50, 91, 16))
        self.label_19.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(60, 60, 71, 16))
        self.label_20.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(300, 0, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_21.setObjectName("label_21")
        self.label_32 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_32.setGeometry(QtCore.QRect(-10, 0, 811, 601))
        self.label_32.setStyleSheet("border-image: url(Green and Orange Modern Grocery Store Banner Landscape (1).png);")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.table_cust = QtWidgets.QTableWidget(parent=self.tab_4)
        self.table_cust.setGeometry(QtCore.QRect(430, 70, 281, 301))
        self.table_cust.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.table_cust.setObjectName("table_cust")
        self.table_cust.setColumnCount(0)
        self.table_cust.setRowCount(0)
        self.label_32.raise_()
        self.cust_tambah.raise_()
        self.cust_edit.raise_()
        self.label_17.raise_()
        self.cust_nama.raise_()
        self.cust_alamat.raise_()
        self.cust_hapus.raise_()
        self.cust_contact.raise_()
        self.cust_refresh.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.table_cust.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        AdminWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=AdminWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 36))
        self.menubar.setObjectName("menubar")
        self.menuPengguna = QtWidgets.QMenu(parent=self.menubar)
        self.menuPengguna.setObjectName("menuPengguna")
        self.menuKelola = QtWidgets.QMenu(parent=self.menubar)
        self.menuKelola.setObjectName("menuKelola")
        self.menuBantuan = QtWidgets.QMenu(parent=self.menubar)
        self.menuBantuan.setObjectName("menuBantuan")
        AdminWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=AdminWindow)
        self.statusbar.setObjectName("statusbar")
        AdminWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtGui.QAction(parent=AdminWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionProfil = QtGui.QAction(parent=AdminWindow)
        self.actionProfil.setObjectName("actionProfil")
        self.actionLogout = QtGui.QAction(parent=AdminWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionBarang = QtGui.QAction(parent=AdminWindow)
        self.actionBarang.setObjectName("actionBarang")
        self.actionPengguna = QtGui.QAction(parent=AdminWindow)
        self.actionPengguna.setObjectName("actionPengguna")
        self.actionCustomer = QtGui.QAction(parent=AdminWindow)
        self.actionCustomer.setObjectName("actionCustomer")
        self.actionTransaksi = QtGui.QAction(parent=AdminWindow)
        self.actionTransaksi.setObjectName("actionTransaksi")
        self.actionTentang = QtGui.QAction(parent=AdminWindow)
        self.actionTentang.setObjectName("actionTentang")
        self.actionDokumentasi = QtGui.QAction(parent=AdminWindow)
        self.actionDokumentasi.setObjectName("actionDokumentasi")
        self.actionTeam = QtGui.QAction(parent=AdminWindow)
        self.actionTeam.setObjectName("actionTeam")
        self.menuPengguna.addAction(self.actionLogin)
        self.menuPengguna.addAction(self.actionProfil)
        self.menuPengguna.addAction(self.actionLogout)
        self.menuKelola.addAction(self.actionBarang)
        self.menuKelola.addAction(self.actionPengguna)
        self.menuKelola.addAction(self.actionCustomer)
        self.menuKelola.addAction(self.actionTransaksi)
        self.menuBantuan.addAction(self.actionTentang)
        self.menuBantuan.addAction(self.actionDokumentasi)
        self.menuBantuan.addAction(self.actionTeam)
        self.menubar.addAction(self.menuPengguna.menuAction())
        self.menubar.addAction(self.menuKelola.menuAction())
        self.menubar.addAction(self.menuBantuan.menuAction())

        self.retranslateUi(AdminWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "MainWindow"))
        self.label_3.setText(_translate("AdminWindow", "Manage Pengguna"))
        self.label_4.setText(_translate("AdminWindow", "Nama"))
        self.label_5.setText(_translate("AdminWindow", "Username"))
        self.label_6.setText(_translate("AdminWindow", "Password"))
        self.label_7.setText(_translate("AdminWindow", "Salary"))
        self.label_8.setText(_translate("AdminWindow", "Role"))
        self.emp_tambah.setText(_translate("AdminWindow", "Tambah"))
        self.label_9.setText(_translate("AdminWindow", "List Pengguna"))
        self.emp_refresh.setText(_translate("AdminWindow", "Refresh"))
        self.emp_hapus.setText(_translate("AdminWindow", "Hapus"))
        self.emp_edit.setText(_translate("AdminWindow", "Edit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("AdminWindow", "Manage Pengguna"))
        self.label_22.setText(_translate("AdminWindow", "List Barang"))
        self.barang_hapus.setText(_translate("AdminWindow", "Hapus"))
        self.label_23.setText(_translate("AdminWindow", "Nama"))
        self.label_24.setText(_translate("AdminWindow", "Buy Price"))
        self.label_25.setText(_translate("AdminWindow", "Manage Barang"))
        self.barang_edit.setText(_translate("AdminWindow", "Edit"))
        self.barang_tambah.setText(_translate("AdminWindow", "Tambah"))
        self.label_26.setText(_translate("AdminWindow", "Sell Price"))
        self.barang_refresh.setText(_translate("AdminWindow", "Refresh"))
        self.label_27.setText(_translate("AdminWindow", "Quantity"))
        self.label_28.setText(_translate("AdminWindow", "Supplier"))
        self.label_29.setText(_translate("AdminWindow", "Expire Date"))
        self.label_30.setText(_translate("AdminWindow", "Barang Check"))
        self.barang_check.setText(_translate("AdminWindow", "Check"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("AdminWindow", "Manage Barang"))
        self.supp_edit.setText(_translate("AdminWindow", "Edit"))
        self.supp_refresh.setText(_translate("AdminWindow", "Refresh"))
        self.supp_tambah.setText(_translate("AdminWindow", "Tambah"))
        self.label_12.setText(_translate("AdminWindow", "Contact"))
        self.label_13.setText(_translate("AdminWindow", "Alamat"))
        self.label_14.setText(_translate("AdminWindow", "Manage Supplier"))
        self.label_15.setText(_translate("AdminWindow", "Nama"))
        self.label_16.setText(_translate("AdminWindow", "List Supplier"))
        self.supp_hapus.setText(_translate("AdminWindow", "Hapus"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("AdminWindow", "Manage Supplier"))
        self.cust_tambah.setText(_translate("AdminWindow", "Tambah"))
        self.cust_edit.setText(_translate("AdminWindow", "Edit"))
        self.label_17.setText(_translate("AdminWindow", "Contact"))
        self.cust_hapus.setText(_translate("AdminWindow", "Hapus"))
        self.cust_refresh.setText(_translate("AdminWindow", "Refresh"))
        self.label_18.setText(_translate("AdminWindow", "Alamat"))
        self.label_19.setText(_translate("AdminWindow", "List Customer"))
        self.label_20.setText(_translate("AdminWindow", "Nama"))
        self.label_21.setText(_translate("AdminWindow", "Manage Customer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("AdminWindow", "Manage Customer"))
        self.menuPengguna.setTitle(_translate("AdminWindow", "Pengguna"))
        self.menuKelola.setTitle(_translate("AdminWindow", "Kelola"))
        self.menuBantuan.setTitle(_translate("AdminWindow", "Bantuan"))
        self.actionLogin.setText(_translate("AdminWindow", "Login"))
        self.actionProfil.setText(_translate("AdminWindow", "Profil"))
        self.actionLogout.setText(_translate("AdminWindow", "Logout"))
        self.actionBarang.setText(_translate("AdminWindow", "Barang"))
        self.actionPengguna.setText(_translate("AdminWindow", "Pengguna"))
        self.actionCustomer.setText(_translate("AdminWindow", "Customer"))
        self.actionTransaksi.setText(_translate("AdminWindow", "Transaksi"))
        self.actionTentang.setText(_translate("AdminWindow", "Tentang"))
        self.actionDokumentasi.setText(_translate("AdminWindow", "Dokumentasi"))
        self.actionTeam.setText(_translate("AdminWindow", "Team"))
