# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PetugasWindow(object):
    def setupUi(self, PetugasWindow):
        PetugasWindow.setObjectName("PetugasWindow")
        PetugasWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=PetugasWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 10, 811, 541))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_6 = QtWidgets.QLabel(parent=self.tab)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 811, 601))
        self.label_6.setStyleSheet("border-image: url(Green and Orange Modern Grocery Store Banner Landscape (1).png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.tab)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 50, 751, 401))
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_22 = QtWidgets.QLabel(parent=self.page)
        self.label_22.setGeometry(QtCore.QRect(50, 20, 91, 16))
        self.label_22.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_22.setObjectName("label_22")
        self.barang_preview = QtWidgets.QPushButton(parent=self.page)
        self.barang_preview.setGeometry(QtCore.QRect(450, 300, 81, 31))
        self.barang_preview.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(25, 135, 84);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(25, 135, 84, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(25, 135, 84, 200);\n"
"}")
        self.barang_preview.setObjectName("barang_preview")
        self.barang_nama = QtWidgets.QLineEdit(parent=self.page)
        self.barang_nama.setGeometry(QtCore.QRect(470, 50, 241, 31))
        self.barang_nama.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_nama.setObjectName("barang_nama")
        self.barang_harga = QtWidgets.QLineEdit(parent=self.page)
        self.barang_harga.setGeometry(QtCore.QRect(470, 90, 241, 31))
        self.barang_harga.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_harga.setObjectName("barang_harga")
        self.barang_stok = QtWidgets.QLineEdit(parent=self.page)
        self.barang_stok.setGeometry(QtCore.QRect(470, 130, 241, 31))
        self.barang_stok.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_stok.setObjectName("barang_stok")
        self.barang_addCart = QtWidgets.QPushButton(parent=self.page)
        self.barang_addCart.setGeometry(QtCore.QRect(540, 300, 81, 31))
        self.barang_addCart.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background: rgb(13, 110, 253)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(13, 110, 253, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(13, 110, 253, 200);\n"
"}\n"
"\n"
"")
        self.barang_addCart.setObjectName("barang_addCart")
        self.label_27 = QtWidgets.QLabel(parent=self.page)
        self.label_27.setGeometry(QtCore.QRect(360, 180, 71, 16))
        self.label_27.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_27.setObjectName("label_27")
        self.label_26 = QtWidgets.QLabel(parent=self.page)
        self.label_26.setGeometry(QtCore.QRect(360, 140, 71, 16))
        self.label_26.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_26.setObjectName("label_26")
        self.label_24 = QtWidgets.QLabel(parent=self.page)
        self.label_24.setGeometry(QtCore.QRect(360, 100, 71, 16))
        self.label_24.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_24.setObjectName("label_24")
        self.label_23 = QtWidgets.QLabel(parent=self.page)
        self.label_23.setGeometry(QtCore.QRect(360, 60, 71, 16))
        self.label_23.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_23.setObjectName("label_23")
        self.label_29 = QtWidgets.QLabel(parent=self.page)
        self.label_29.setGeometry(QtCore.QRect(360, 220, 71, 16))
        self.label_29.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_29.setObjectName("label_29")
        self.barang_totalBeli = QtWidgets.QLineEdit(parent=self.page)
        self.barang_totalBeli.setGeometry(QtCore.QRect(470, 250, 241, 31))
        self.barang_totalBeli.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_totalBeli.setObjectName("barang_totalBeli")
        self.label_30 = QtWidgets.QLabel(parent=self.page)
        self.label_30.setGeometry(QtCore.QRect(360, 260, 71, 16))
        self.label_30.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_30.setObjectName("label_30")
        self.barang_supplier = QtWidgets.QComboBox(parent=self.page)
        self.barang_supplier.setGeometry(QtCore.QRect(470, 170, 241, 31))
        self.barang_supplier.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_supplier.setObjectName("barang_supplier")
        self.barang_expired = QtWidgets.QDateEdit(parent=self.page)
        self.barang_expired.setGeometry(QtCore.QRect(470, 210, 241, 31))
        self.barang_expired.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_expired.setObjectName("barang_expired")
        self.barang_viewCart = QtWidgets.QPushButton(parent=self.page)
        self.barang_viewCart.setGeometry(QtCore.QRect(630, 300, 81, 31))
        self.barang_viewCart.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(25, 135, 84);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(25, 135, 84, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(25, 135, 84, 200);\n"
"}")
        self.barang_viewCart.setObjectName("barang_viewCart")
        self.barang_refresh = QtWidgets.QPushButton(parent=self.page)
        self.barang_refresh.setGeometry(QtCore.QRect(360, 300, 81, 31))
        self.barang_refresh.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(108, 117, 125);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(108, 117, 125, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(108, 117, 125, 200);\n"
"}")
        self.barang_refresh.setObjectName("barang_refresh")
        self.table_barang = QtWidgets.QTableWidget(parent=self.page)
        self.table_barang.setGeometry(QtCore.QRect(50, 40, 281, 301))
        self.table_barang.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.table_barang.setObjectName("table_barang")
        self.table_barang.setColumnCount(0)
        self.table_barang.setRowCount(0)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_4 = QtWidgets.QLabel(parent=self.page_2)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.barang_subTotal = QtWidgets.QLineEdit(parent=self.page_2)
        self.barang_subTotal.setGeometry(QtCore.QRect(470, 140, 241, 31))
        self.barang_subTotal.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_subTotal.setObjectName("barang_subTotal")
        self.label_25 = QtWidgets.QLabel(parent=self.page_2)
        self.label_25.setGeometry(QtCore.QRect(360, 150, 71, 16))
        self.label_25.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_25.setObjectName("label_25")
        self.label_28 = QtWidgets.QLabel(parent=self.page_2)
        self.label_28.setGeometry(QtCore.QRect(360, 110, 71, 16))
        self.label_28.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_28.setObjectName("label_28")
        self.barang_customer = QtWidgets.QComboBox(parent=self.page_2)
        self.barang_customer.setGeometry(QtCore.QRect(470, 100, 241, 31))
        self.barang_customer.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_customer.setObjectName("barang_customer")
        self.barang_back = QtWidgets.QPushButton(parent=self.page_2)
        self.barang_back.setGeometry(QtCore.QRect(450, 270, 81, 31))
        self.barang_back.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(108, 117, 125);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(108, 117, 125, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(108, 117, 125, 200);\n"
"}")
        self.barang_back.setObjectName("barang_back")
        self.barang_pay = QtWidgets.QPushButton(parent=self.page_2)
        self.barang_pay.setGeometry(QtCore.QRect(630, 270, 81, 31))
        self.barang_pay.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background: rgb(13, 110, 253)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(13, 110, 253, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(13, 110, 253, 200);\n"
"}\n"
"\n"
"")
        self.barang_pay.setObjectName("barang_pay")
        self.barang_dibayar = QtWidgets.QLineEdit(parent=self.page_2)
        self.barang_dibayar.setGeometry(QtCore.QRect(470, 180, 241, 31))
        self.barang_dibayar.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_dibayar.setText("")
        self.barang_dibayar.setObjectName("barang_dibayar")
        self.label_31 = QtWidgets.QLabel(parent=self.page_2)
        self.label_31.setGeometry(QtCore.QRect(360, 190, 71, 16))
        self.label_31.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_31.setObjectName("label_31")
        self.barang_kembali = QtWidgets.QLineEdit(parent=self.page_2)
        self.barang_kembali.setGeometry(QtCore.QRect(470, 220, 241, 31))
        self.barang_kembali.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.barang_kembali.setText("")
        self.barang_kembali.setObjectName("barang_kembali")
        self.label_32 = QtWidgets.QLabel(parent=self.page_2)
        self.label_32.setGeometry(QtCore.QRect(360, 230, 71, 16))
        self.label_32.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_32.setObjectName("label_32")
        self.jumlah_item = QtWidgets.QLabel(parent=self.page_2)
        self.jumlah_item.setGeometry(QtCore.QRect(60, 370, 131, 16))
        self.jumlah_item.setText("")
        self.jumlah_item.setObjectName("jumlah_item")
        self.barang_delete = QtWidgets.QPushButton(parent=self.page_2)
        self.barang_delete.setGeometry(QtCore.QRect(360, 270, 81, 31))
        self.barang_delete.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(220, 53, 69);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(220, 53, 69, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(220, 53, 69, 200);\n"
"}")
        self.barang_delete.setObjectName("barang_delete")
        self.barang_sum = QtWidgets.QPushButton(parent=self.page_2)
        self.barang_sum.setGeometry(QtCore.QRect(540, 270, 81, 31))
        self.barang_sum.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(25, 135, 84);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(25, 135, 84, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(25, 135, 84, 200);\n"
"}")
        self.barang_sum.setObjectName("barang_sum")
        self.table_cart = QtWidgets.QTableWidget(parent=self.page_2)
        self.table_cart.setGeometry(QtCore.QRect(50, 60, 281, 301))
        self.table_cart.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.table_cart.setObjectName("table_cart")
        self.table_cart.setColumnCount(0)
        self.table_cart.setRowCount(0)
        self.stackedWidget.addWidget(self.page_2)
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setGeometry(QtCore.QRect(331, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.cust_hapus = QtWidgets.QPushButton(parent=self.tab_2)
        self.cust_hapus.setGeometry(QtCore.QRect(540, 370, 81, 31))
        self.cust_hapus.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(220, 53, 69);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(220, 53, 69, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(220, 53, 69, 200);\n"
"}")
        self.cust_hapus.setObjectName("cust_hapus")
        self.label_18 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(70, 130, 71, 16))
        self.label_18.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(70, 90, 71, 16))
        self.label_17.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.cust_refresh = QtWidgets.QPushButton(parent=self.tab_2)
        self.cust_refresh.setGeometry(QtCore.QRect(440, 370, 81, 31))
        self.cust_refresh.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(108, 117, 125);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(108, 117, 125, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(108, 117, 125, 200);\n"
"}")
        self.cust_refresh.setObjectName("cust_refresh")
        self.label_19 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(440, 40, 91, 16))
        self.label_19.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(70, 50, 71, 16))
        self.label_20.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_20.setObjectName("label_20")
        self.cust_nama = QtWidgets.QLineEdit(parent=self.tab_2)
        self.cust_nama.setGeometry(QtCore.QRect(170, 40, 241, 31))
        self.cust_nama.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cust_nama.setObjectName("cust_nama")
        self.cust_contact = QtWidgets.QLineEdit(parent=self.tab_2)
        self.cust_contact.setGeometry(QtCore.QRect(170, 80, 241, 31))
        self.cust_contact.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cust_contact.setObjectName("cust_contact")
        self.cust_edit = QtWidgets.QPushButton(parent=self.tab_2)
        self.cust_edit.setGeometry(QtCore.QRect(640, 370, 81, 31))
        self.cust_edit.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(25, 135, 84);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(25, 135, 84, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(25, 135, 84, 200);\n"
"}")
        self.cust_edit.setObjectName("cust_edit")
        self.cust_tambah = QtWidgets.QPushButton(parent=self.tab_2)
        self.cust_tambah.setGeometry(QtCore.QRect(250, 170, 161, 41))
        self.cust_tambah.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    background: rgb(13, 110, 253)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(13, 110, 253, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(13, 110, 253, 200);\n"
"}\n"
"\n"
"")
        self.cust_tambah.setObjectName("cust_tambah")
        self.cust_alamat = QtWidgets.QLineEdit(parent=self.tab_2)
        self.cust_alamat.setGeometry(QtCore.QRect(170, 120, 241, 31))
        self.cust_alamat.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cust_alamat.setObjectName("cust_alamat")
        self.label_5 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 811, 601))
        self.label_5.setStyleSheet("border-image: url(Green and Orange Modern Grocery Store Banner Landscape (1).png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.table_cust = QtWidgets.QTableWidget(parent=self.tab_2)
        self.table_cust.setGeometry(QtCore.QRect(440, 60, 281, 301))
        self.table_cust.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.table_cust.setObjectName("table_cust")
        self.table_cust.setColumnCount(0)
        self.table_cust.setRowCount(0)
        self.label_5.raise_()
        self.cust_hapus.raise_()
        self.label_18.raise_()
        self.label_17.raise_()
        self.cust_refresh.raise_()
        self.label_20.raise_()
        self.cust_nama.raise_()
        self.cust_contact.raise_()
        self.cust_edit.raise_()
        self.cust_tambah.raise_()
        self.cust_alamat.raise_()
        self.label_19.raise_()
        self.table_cust.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        PetugasWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=PetugasWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 36))
        self.menubar.setObjectName("menubar")
        self.menuPengguna = QtWidgets.QMenu(parent=self.menubar)
        self.menuPengguna.setObjectName("menuPengguna")
        self.menuKelola = QtWidgets.QMenu(parent=self.menubar)
        self.menuKelola.setObjectName("menuKelola")
        self.menuBantuan = QtWidgets.QMenu(parent=self.menubar)
        self.menuBantuan.setObjectName("menuBantuan")
        PetugasWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=PetugasWindow)
        self.statusbar.setObjectName("statusbar")
        PetugasWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtGui.QAction(parent=PetugasWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionProfil = QtGui.QAction(parent=PetugasWindow)
        self.actionProfil.setObjectName("actionProfil")
        self.actionLogout = QtGui.QAction(parent=PetugasWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionBarang = QtGui.QAction(parent=PetugasWindow)
        self.actionBarang.setObjectName("actionBarang")
        self.actionPengguna = QtGui.QAction(parent=PetugasWindow)
        self.actionPengguna.setObjectName("actionPengguna")
        self.actionTransaksi = QtGui.QAction(parent=PetugasWindow)
        self.actionTransaksi.setObjectName("actionTransaksi")
        self.actionTentang = QtGui.QAction(parent=PetugasWindow)
        self.actionTentang.setObjectName("actionTentang")
        self.actionDokumentasi = QtGui.QAction(parent=PetugasWindow)
        self.actionDokumentasi.setObjectName("actionDokumentasi")
        self.actionTeam = QtGui.QAction(parent=PetugasWindow)
        self.actionTeam.setObjectName("actionTeam")
        self.actionCustomer = QtGui.QAction(parent=PetugasWindow)
        self.actionCustomer.setObjectName("actionCustomer")
        self.menuPengguna.addAction(self.actionLogin)
        self.menuPengguna.addAction(self.actionProfil)
        self.menuPengguna.addAction(self.actionLogout)
        self.menuKelola.addAction(self.actionBarang)
        self.menuKelola.addAction(self.actionPengguna)
        self.menuKelola.addAction(self.actionCustomer)
        self.menuKelola.addAction(self.actionTransaksi)
        self.menuBantuan.addAction(self.actionTentang)
        self.menuBantuan.addAction(self.actionDokumentasi)
        self.menuBantuan.addAction(self.actionTeam)
        self.menubar.addAction(self.menuPengguna.menuAction())
        self.menubar.addAction(self.menuKelola.menuAction())
        self.menubar.addAction(self.menuBantuan.menuAction())

        self.retranslateUi(PetugasWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PetugasWindow)

    def retranslateUi(self, PetugasWindow):
        _translate = QtCore.QCoreApplication.translate
        PetugasWindow.setWindowTitle(_translate("PetugasWindow", "MainWindow"))
        self.label_22.setText(_translate("PetugasWindow", "List Barang"))
        self.barang_preview.setText(_translate("PetugasWindow", "Preview"))
        self.barang_addCart.setText(_translate("PetugasWindow", "Add Cart"))
        self.label_27.setText(_translate("PetugasWindow", "Supplier"))
        self.label_26.setText(_translate("PetugasWindow", "Stok"))
        self.label_24.setText(_translate("PetugasWindow", "Harga"))
        self.label_23.setText(_translate("PetugasWindow", "Nama"))
        self.label_29.setText(_translate("PetugasWindow", "Expire Date"))
        self.label_30.setText(_translate("PetugasWindow", "Total Beli"))
        self.barang_viewCart.setText(_translate("PetugasWindow", "View Cart"))
        self.barang_refresh.setText(_translate("PetugasWindow", "Refresh"))
        self.label_4.setText(_translate("PetugasWindow", "Keranjang"))
        self.label_25.setText(_translate("PetugasWindow", "Sub Total"))
        self.label_28.setText(_translate("PetugasWindow", "Customer"))
        self.barang_back.setText(_translate("PetugasWindow", "Back"))
        self.barang_pay.setText(_translate("PetugasWindow", "Pay"))
        self.label_31.setText(_translate("PetugasWindow", "Dibayar"))
        self.label_32.setText(_translate("PetugasWindow", "Kembali"))
        self.barang_delete.setText(_translate("PetugasWindow", "Delete"))
        self.barang_sum.setText(_translate("PetugasWindow", "SUM"))
        self.label_3.setText(_translate("PetugasWindow", "Grocery Store"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PetugasWindow", "Grocery Store"))
        self.cust_hapus.setText(_translate("PetugasWindow", "Hapus"))
        self.label_18.setText(_translate("PetugasWindow", "Alamat"))
        self.label_17.setText(_translate("PetugasWindow", "Contact"))
        self.cust_refresh.setText(_translate("PetugasWindow", "Refresh"))
        self.label_19.setText(_translate("PetugasWindow", "List Customer"))
        self.label_20.setText(_translate("PetugasWindow", "Nama"))
        self.cust_edit.setText(_translate("PetugasWindow", "Edit"))
        self.cust_tambah.setText(_translate("PetugasWindow", "Tambah"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PetugasWindow", "Customer Area"))
        self.menuPengguna.setTitle(_translate("PetugasWindow", "Pengguna"))
        self.menuKelola.setTitle(_translate("PetugasWindow", "Kelola"))
        self.menuBantuan.setTitle(_translate("PetugasWindow", "Bantuan"))
        self.actionLogin.setText(_translate("PetugasWindow", "Login"))
        self.actionProfil.setText(_translate("PetugasWindow", "Profil"))
        self.actionLogout.setText(_translate("PetugasWindow", "Logout"))
        self.actionBarang.setText(_translate("PetugasWindow", "Barang"))
        self.actionPengguna.setText(_translate("PetugasWindow", "Pengguna"))
        self.actionTransaksi.setText(_translate("PetugasWindow", "Transaksi"))
        self.actionTentang.setText(_translate("PetugasWindow", "Tentang"))
        self.actionDokumentasi.setText(_translate("PetugasWindow", "Dokumentasi"))
        self.actionTeam.setText(_translate("PetugasWindow", "Team"))
        self.actionCustomer.setText(_translate("PetugasWindow", "Customer"))
